[dns]
name_server = "223.5.5.5"

[web]
address = "0.0.0.0:9113"

[[targets]]
addr = "223.5.5.5"
[targets.labels]
"some_label" = "test"


[[targets]]
addr = "114.114.114.114"
[targets.labels]
"custom_label" = "hihihihi"

[global_labels]
"from" = "192.168.2.1"
"from_host" = "m1"
